### ISSUE TITLE
Baseline?

### ISSUE THREAD

**Issue by a897456** [facebookresearch/AudioDec#22]
https://github.com/facebookresearch/AudioDec/blob/5ec3ab9d53cff2f4d92163c0624a277d173703a5/codecTrain.py#L22-L25
![image](https://github.com/facebookresearch/AudioDec/assets/28752526/7cc54449-2091-4622-90fd-308e39c98c0f)
Hi @bigpon 
It is mentioned in the paper that baseline is soundstream, but there is no `wav_discriminator` or `stft_discriminator` of soundstream in your code, just only  `mel_loss`. 
Is it better to keep only `mel_loss` than `adv_loss` `feat_loss` `com_loss` of soundstream? This is a great discovery.

**Comment by bigpon** [comment]
>Is it better to keep only mel_loss than adv_loss feat_loss com_loss of soundstream? This is a great discovery.
No, AudioDec still needs the GAN losses for the second stage, and the second stage is essential.
Please carefully check the paper.

**Comment by bigpon** [comment]
symAD is the symmetric AudioDec, which is not the SoundStream.
We don't provide SoundStream implementation since this repo focuses on providing AudioDec implementation.

The decoder you used is only the first stage of symAD, which is trained without GAN.
We fix the encoder in the second stage, so you can use the first stage for tx but you have to use the second stage model for rx (e.g. rx_steps = 1000000)

**Comment by a897456** [comment]
> > Is it better to keep only mel_loss than adv_loss feat_loss com_loss of soundstream? This is a great discovery.
> 
> No, AudioDec still needs the GAN losses for the second stage, and the second stage is essential. Please carefully check the paper.

At first, I thought you used adv_loss and feat_loss to replace wav and stft discriminators. The loss of these two discriminators is exactly the same, so I call it a great discovery
