### ISSUE TITLE
Fix the encoder

### ISSUE THREAD

**Issue by a897456** [facebookresearch/AudioDec#23]
first: model_type: symAudioDec

1. start_steps:                       
    generator: 0
    discriminator: 0
train_max_steps: 500000            
adv_train_max_steps: 500000
 

2. start_steps:                       
    generator: 0
    discriminator: 500000
train_max_steps: 500000            
adv_train_max_steps: 1000000

1. Which configuration would be faster or more efficient?
2. My opinion is that both configurations train the 500k step (with discriminator), but if you change the discriminator type, there is a difference between the two: 

- The first configuration, 500k step  (with discriminator) needs to be trained from the beginning.
- The second configuration can load 500k step(without discriminator) and then continue 500k step(with discriminator)
- And finally, both of them actually train the 500k step (with discriminator), but the effect or time, I do not know which one is more dominant

**Comment by bigpon** [comment]
Since the training of the discriminators dominates the training time, the training time difference between 1 and 2 is small (1 might be slightly faster).

However, we propose the 2-stage training paradigm (e.g. config 2) because of the training stability.
Directly training both the codec and discriminators easily has an unstable training issue.  
Moreover, the 2-stage training makes it possible to replace the encoder for denoising or the decoder for binaural rendering easily.

**Comment by a897456** [comment]
> Moreover, the 2-stage training makes it possible to replace the encoder for denoising or the decoder for binaural rendering easily.

Can I assume that the training results of the first 500k step, such as this file: `exp/autoencoder/symAD_libritts_24000_hop300/ checkpot-500000steps.pkl` which can be shared, when you use it, just load it directly.
For example, if I want to replace the HIFIGAN discriminator with the WAV discriminator, load it directly and set the configuration to 1 as above.  Right?

**Comment by bigpon** [comment]
Yes, you can.
However, please check the trainer/train in detail to make sure the overall behavior matches what you plan to do.
