### ISSUE TITLE
Samplerates' affect on hyperparameters

### ISSUE THREAD

**Issue by fmac2000** [facebookresearch/AudioDec#4]
Hi Authors,

Great work, I'm sure to use this going forward. I have a question however, given the encoder and vocoder, what hyperparameters are affected when the samplerate is changed? I'm looking to instead use 16khz audio instead of 48khz. For the sake of simplicity, let us use the configuration files described in the [readme](https://github.com/facebookresearch/AudioDec/tree/main#training-and-testing-the-whole-audiodec-pipeline).

Thank you, congratulations on the release!

**Comment by bigpon** [comment]
Hi, 
thanks!

Although we did not officially evaluate the system with 16 kHz audio, we did quickly evaluate the system using downsampled VCTK. According to our experience, you only need to modify the following parameters in the config file (ex: config/autoencoder/symAD_vctk_48000_hop300.yaml) to run the 16kHz training and testing.
1. sampling_rate: &sampling_rate 16000
2. data:
        path: xxxx (the path of 16 kHz corpus)
3. generator_params:
        enc_strides: [2, 4, 5, 5]
        dec_strides: [5, 5, 4, 2]
4. mel_loss_params:
        hop_sizes: [200]
        fmax: 7600
It is fine to keep the same batch size or reduce it according to your hardware memory.

**Comment by bigpon** [comment]
The parameters are empirically set. 
Specifically, the down/up sample rate (enc_/dec_strides) follows the original SoundStream paper (hop_length of 300 samples for 24 kHz), and we set the hop_length of 200 samples for 16 kHz to keep the same hop_length in second (12.5 ms). However, we found that the hop_length of 600 samples doesn’t work well for 48 kHz, so we still set the hop_length of 300 samples for 48 kHz audio. 
Since we didn’t comprehensively evaluate the performance with many different hop lengths, 300 samples for 48 kHz might not be the optimized value.

In addition, the mel_loss_params follows the setting of the parallel WaveGAN repo [https://github.com/kan-bayashi/ParallelWaveGAN], which is also empirically set.
